// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiskPulse.Data;

#nullable disable

namespace RiskPulse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816161300_UserPermissionControl")]
    partial class UserPermissionControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("riskpulse")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiskPulse.Data.Entries.AssessmentHeader", b =>
                {
                    b.Property<int>("AssessmentHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssessmentHeaderId"));

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssessmentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("KriHeaderId")
                        .HasColumnType("integer");

                    b.Property<int?>("RiskRegisterHeaderId")
                        .HasColumnType("integer");

                    b.Property<int?>("SaqHeaderId")
                        .HasColumnType("integer");

                    b.HasKey("AssessmentHeaderId");

                    b.HasIndex("KriHeaderId");

                    b.HasIndex("SaqHeaderId");

                    b.ToTable("AssessmentHeaders", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GroupId");

                    b.ToTable("Groups", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Kri", b =>
                {
                    b.Property<int>("KriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KriId"));

                    b.Property<bool>("AllowComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("KriDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KriHeaderId")
                        .HasColumnType("integer");

                    b.Property<int>("KriThresholdGroupId")
                        .HasColumnType("integer");

                    b.HasKey("KriId");

                    b.HasIndex("KriHeaderId");

                    b.HasIndex("KriThresholdGroupId");

                    b.ToTable("Kris", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriHeader", b =>
                {
                    b.Property<int>("KriHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KriHeaderId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("KriHeaderDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KriStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("KriHeaderId");

                    b.HasIndex("GroupId");

                    b.ToTable("KriHeaders", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriThreshold", b =>
                {
                    b.Property<int>("KriThresholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KriThresholdId"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("KriThresholdGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.HasKey("KriThresholdId");

                    b.HasIndex("ColorId");

                    b.HasIndex("KriThresholdGroupId");

                    b.ToTable("KriThresholds", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriThresholdColor", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColorId"));

                    b.Property<string>("ColorDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ColorId");

                    b.ToTable("KriThresholdColors", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriThresholdGroup", b =>
                {
                    b.Property<int>("KriThresholdGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KriThresholdGroupId"));

                    b.Property<string>("KriThresholdGroupDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KriThresholdGroupId");

                    b.ToTable("KriThresholdGroups", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("DefaultPermissionId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.HasIndex("DefaultPermissionId");

                    b.ToTable("Roles", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolePermissionId"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.SaqHeader", b =>
                {
                    b.Property<int>("SaqHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaqHeaderId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("SaqDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaqStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("SaqHeaderId");

                    b.HasIndex("GroupId");

                    b.ToTable("SaqHeaders", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.SaqQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<bool>("AllowComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SaqHeaderId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex("SaqHeaderId");

                    b.ToTable("SaqQuestions", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.SaqQuestionOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptionId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("SaqQuestionOptions", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.ScheduleHeader", b =>
                {
                    b.Property<int>("ScheduleHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleHeaderId"));

                    b.Property<int>("AssessmentHeaderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScheduleDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduleHeaderId");

                    b.HasIndex("AssessmentHeaderId");

                    b.ToTable("ScheduleHeaders", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UnitId");

                    b.ToTable("Units", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.UnitGroup", b =>
                {
                    b.Property<int>("UnitGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitGroupId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("UnitGroupId");

                    b.HasIndex("UnitId");

                    b.HasIndex("GroupId", "UnitId")
                        .IsUnique();

                    b.ToTable("UnitGroups", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UnitId");

                    b.ToTable("Users", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.AssessmentHeader", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.KriHeader", "KriHeader")
                        .WithMany("AssessmentHeaders")
                        .HasForeignKey("KriHeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RiskPulse.Data.Entries.SaqHeader", "SaqHeader")
                        .WithMany("AssessmentHeaders")
                        .HasForeignKey("SaqHeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KriHeader");

                    b.Navigation("SaqHeader");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Kri", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.KriHeader", "KriHeader")
                        .WithMany("Kris")
                        .HasForeignKey("KriHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiskPulse.Data.Entries.KriThresholdGroup", "KriThresholdGroup")
                        .WithMany("Kris")
                        .HasForeignKey("KriThresholdGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KriHeader");

                    b.Navigation("KriThresholdGroup");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriHeader", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.Group", "Group")
                        .WithMany("KriHeaders")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriThreshold", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.KriThresholdColor", "Color")
                        .WithMany("KriThresholds")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiskPulse.Data.Entries.KriThresholdGroup", "KriThresholdGroup")
                        .WithMany("KriThresholds")
                        .HasForeignKey("KriThresholdGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("KriThresholdGroup");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Role", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.Permission", "DefaultPermission")
                        .WithMany()
                        .HasForeignKey("DefaultPermissionId");

                    b.Navigation("DefaultPermission");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.RolePermission", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiskPulse.Data.Entries.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.SaqHeader", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.Group", "Group")
                        .WithMany("SaqHeaders")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.SaqQuestion", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.SaqHeader", "SaqHeader")
                        .WithMany("SaqQuestions")
                        .HasForeignKey("SaqHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaqHeader");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.SaqQuestionOption", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.SaqQuestion", "SaqQuestion")
                        .WithMany("SaqQuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaqQuestion");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.ScheduleHeader", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.AssessmentHeader", "AssessmentHeader")
                        .WithMany("ScheduleHeaders")
                        .HasForeignKey("AssessmentHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentHeader");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.UnitGroup", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.Group", "Group")
                        .WithMany("UnitGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiskPulse.Data.Entries.Unit", "Unit")
                        .WithMany("UnitGroups")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.User", b =>
                {
                    b.HasOne("RiskPulse.Data.Entries.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiskPulse.Data.Entries.Unit", "Unit")
                        .WithMany("Users")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.AssessmentHeader", b =>
                {
                    b.Navigation("ScheduleHeaders");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Group", b =>
                {
                    b.Navigation("KriHeaders");

                    b.Navigation("SaqHeaders");

                    b.Navigation("UnitGroups");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriHeader", b =>
                {
                    b.Navigation("AssessmentHeaders");

                    b.Navigation("Kris");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriThresholdColor", b =>
                {
                    b.Navigation("KriThresholds");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.KriThresholdGroup", b =>
                {
                    b.Navigation("KriThresholds");

                    b.Navigation("Kris");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.SaqHeader", b =>
                {
                    b.Navigation("AssessmentHeaders");

                    b.Navigation("SaqQuestions");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.SaqQuestion", b =>
                {
                    b.Navigation("SaqQuestionOptions");
                });

            modelBuilder.Entity("RiskPulse.Data.Entries.Unit", b =>
                {
                    b.Navigation("UnitGroups");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
