// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiskPulse.Data;

#nullable disable

namespace RiskPulse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811183521_saq")]
    partial class saq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("riskpulse")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("DefaultPermissionId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.HasIndex("DefaultPermissionId");

                    b.ToTable("Roles", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolePermissionId"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UnitId");

                    b.ToTable("Units", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UnitId");

                    b.ToTable("Users", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.Saq.SaqHeader", b =>
                {
                    b.Property<int>("SaqHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaqHeaderId"));

                    b.Property<string>("SaqDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaqStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("SaqHeaderId");

                    b.ToTable("SaqHeaders", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.Saq.SaqQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SaqHeaderId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex("SaqHeaderId");

                    b.ToTable("SaqQuestions", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.Saq.SaqQuestionOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptionId"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionValue")
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SaqQuestionQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("OptionId");

                    b.HasIndex("SaqQuestionQuestionId");

                    b.ToTable("SaqQuestionOptions", "riskpulse");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.Role", b =>
                {
                    b.HasOne("RiskPulse.Models.DbModel.AccessControl.Permission", "DefaultPermission")
                        .WithMany()
                        .HasForeignKey("DefaultPermissionId");

                    b.Navigation("DefaultPermission");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.RolePermission", b =>
                {
                    b.HasOne("RiskPulse.Models.DbModel.AccessControl.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiskPulse.Models.DbModel.AccessControl.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.User", b =>
                {
                    b.HasOne("RiskPulse.Models.DbModel.AccessControl.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiskPulse.Models.DbModel.AccessControl.Unit", "Unit")
                        .WithMany("Users")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.Saq.SaqQuestion", b =>
                {
                    b.HasOne("RiskPulse.Models.DbModel.Saq.SaqHeader", "SaqHeader")
                        .WithMany("SaqQuestions")
                        .HasForeignKey("SaqHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaqHeader");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.Saq.SaqQuestionOption", b =>
                {
                    b.HasOne("RiskPulse.Models.DbModel.Saq.SaqQuestion", "SaqQuestion")
                        .WithMany("SaqQuestionOptions")
                        .HasForeignKey("SaqQuestionQuestionId");

                    b.Navigation("SaqQuestion");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.AccessControl.Unit", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.Saq.SaqHeader", b =>
                {
                    b.Navigation("SaqQuestions");
                });

            modelBuilder.Entity("RiskPulse.Models.DbModel.Saq.SaqQuestion", b =>
                {
                    b.Navigation("SaqQuestionOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
